### ISSUE TITLE
Gunrock does not build on Cuda 11.7

### ISSUE THREAD

**Issue by sam0oneau** [gunrock/gunrock#917] opened 2022-07-31 22:33 UTC
I am running Cuda 11.7 on Ubuntu LTS 18.04 (WSL). Gunrock fails to build gunrock_generated_hits_app.cu.o due to an argument issue with Cuda Cooperative Primitives (Cub). 

I missed this Issue originally: https://github.com/gunrock/gunrock/issues/905#issuecomment-1024995971
~~If this works, I will mark this as resolved.~~
Still unresolved 

**Example:**
```
sam0oneau@DESKTOP-3913TJA:~/GSM/gunrock/build$ make
[  0%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/archivertest.dir/archiver/archiver.cpp.o
[  0%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/archivertest.dir/archiver/archivertest.cpp.o
[  1%] Linking CXX executable ../../../bin/archivertest
[  1%] Built target archivertest
[  2%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o
[  2%] Linking CXX executable ../../../bin/capitalize
[  2%] Built target capitalize
[  3%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/condense.dir/condense/condense.cpp.o
[  3%] Linking CXX executable ../../../bin/condense
[  3%] Built target condense
[  3%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/filterkey.dir/filterkey/filterkey.cpp.o
[  4%] Linking CXX executable ../../../bin/filterkey
[  4%] Built target filterkey
[  4%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/filterkeydom.dir/filterkeydom/filterkeydom.cpp.o
[  5%] Linking CXX executable ../../../bin/filterkeydom
[  5%] Built target filterkeydom
[  5%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/jsonx.dir/jsonx/jsonx.cpp.o
[  6%] Linking CXX executable ../../../bin/jsonx
[  6%] Built target jsonx
[  6%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/lookaheadparser.dir/lookaheadparser/lookaheadparser.cpp.o
[  7%] Linking CXX executable ../../../bin/lookaheadparser
[  7%] Built target lookaheadparser
[  8%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/messagereader.dir/messagereader/messagereader.cpp.o
[  8%] Linking CXX executable ../../../bin/messagereader
[  8%] Built target messagereader
[  8%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/parsebyparts.dir/parsebyparts/parsebyparts.cpp.o
[  9%] Linking CXX executable ../../../bin/parsebyparts
[  9%] Built target parsebyparts
[ 10%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/pretty.dir/pretty/pretty.cpp.o
[ 10%] Linking CXX executable ../../../bin/pretty
[ 10%] Built target pretty
[ 11%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/prettyauto.dir/prettyauto/prettyauto.cpp.o
[ 11%] Linking CXX executable ../../../bin/prettyauto
[ 11%] Built target prettyauto
[ 11%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/schemavalidator.dir/schemavalidator/schemavalidator.cpp.o
[ 12%] Linking CXX executable ../../../bin/schemavalidator
[ 12%] Built target schemavalidator
[ 12%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/serialize.dir/serialize/serialize.cpp.o
[ 12%] Linking CXX executable ../../../bin/serialize
[ 12%] Built target serialize
[ 12%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/simpledom.dir/simpledom/simpledom.cpp.o
[ 12%] Linking CXX executable ../../../bin/simpledom
[ 12%] Built target simpledom
[ 13%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/simplereader.dir/simplereader/simplereader.cpp.o
[ 13%] Linking CXX executable ../../../bin/simplereader
[ 13%] Built target simplereader
[ 14%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/simplepullreader.dir/simplepullreader/simplepullreader.cpp.o
[ 14%] Linking CXX executable ../../../bin/simplepullreader
[ 14%] Built target simplepullreader
[ 14%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/simplewriter.dir/simplewriter/simplewriter.cpp.o
[ 15%] Linking CXX executable ../../../bin/simplewriter
[ 15%] Built target simplewriter
[ 16%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/sortkeys.dir/sortkeys/sortkeys.cpp.o
[ 16%] Linking CXX executable ../../../bin/sortkeys
[ 16%] Built target sortkeys
[ 16%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/tutorial.dir/tutorial/tutorial.cpp.o
[ 16%] Linking CXX executable ../../../bin/tutorial
[ 16%] Built target tutorial
[ 16%] Built target examples
[ 16%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/namespacetest.dir/namespacetest.cpp.o
[ 17%] Linking CXX static library ../../../../lib/libnamespacetest.a
[ 17%] Built target namespacetest
[ 17%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 18%] Linking CXX static library ../lib/libgtest.a
[ 18%] Built target gtest
[ 18%] Building CXX object googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 18%] Linking CXX static library ../lib/libgtest_main.a
[ 18%] Built target gtest_main
[ 19%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/allocatorstest.cpp.o
[ 19%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/bigintegertest.cpp.o
[ 20%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/cursorstreamwrappertest.cpp.o
[ 20%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/documenttest.cpp.o
[ 20%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/dtoatest.cpp.o
[ 21%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/encodedstreamtest.cpp.o
[ 21%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/encodingstest.cpp.o
[ 22%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/fwdtest.cpp.o
[ 22%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/filestreamtest.cpp.o
[ 22%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/itoatest.cpp.o
[ 23%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/istreamwrappertest.cpp.o
[ 23%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/jsoncheckertest.cpp.o
[ 24%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/namespacetest.cpp.o
[ 24%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/pointertest.cpp.o
[ 24%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/prettywritertest.cpp.o
[ 25%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/ostreamwrappertest.cpp.o
[ 25%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/readertest.cpp.o
[ 26%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/regextest.cpp.o
[ 26%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/schematest.cpp.o
[ 26%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/simdtest.cpp.o
[ 27%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/strfunctest.cpp.o
[ 27%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/stringbuffertest.cpp.o
[ 28%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/strtodtest.cpp.o
[ 28%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/unittest.cpp.o
[ 28%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/valuetest.cpp.o
[ 29%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/writertest.cpp.o
[ 29%] Linking CXX executable ../../../../bin/unittest
[ 29%] Built target unittest
[ 29%] Building CXX object _deps/rapidjson-build/test/perftest/CMakeFiles/perftest.dir/misctest.cpp.o
[ 29%] Building CXX object _deps/rapidjson-build/test/perftest/CMakeFiles/perftest.dir/perftest.cpp.o
[ 30%] Building CXX object _deps/rapidjson-build/test/perftest/CMakeFiles/perftest.dir/platformtest.cpp.o
[ 30%] Building CXX object _deps/rapidjson-build/test/perftest/CMakeFiles/perftest.dir/rapidjsontest.cpp.o
[ 31%] Building CXX object _deps/rapidjson-build/test/perftest/CMakeFiles/perftest.dir/schematest.cpp.o
[ 31%] Linking CXX executable ../../../../bin/perftest
[ 31%] Built target perftest
[ 31%] Built target tests
[ 31%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/util/gunrock_generated_test_utils.cu.o
[ 31%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/hits/gunrock_generated_hits_app.cu.o
/home/sam0oneau/GSM/gunrock/gunrock/util/reduce_device.cuh(86): error: too few arguments for class template "cub::DispatchSegmentedReduce"

/home/sam0oneau/GSM/gunrock/gunrock/util/reduce_device.cuh(100): error: too few arguments for class template "cub::DispatchSegmentedReduce"

2 errors detected in the compilation of "/home/sam0oneau/GSM/gunrock/gunrock/app/hits/hits_app.cu".
CMake Error at gunrock_generated_hits_app.cu.o.RelWithDebInfo.cmake:280 (message):
  Error generating file
  /home/sam0oneau/GSM/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/hits/./gunrock_generated_hits_app.cu.o


gunrock/CMakeFiles/gunrock.dir/build.make:82: recipe for target 'gunrock/CMakeFiles/gunrock.dir/app/hits/gunrock_generated_hits_app.cu.o' failed
make[2]: *** [gunrock/CMakeFiles/gunrock.dir/app/hits/gunrock_generated_hits_app.cu.o] Error 1
CMakeFiles/Makefile2:2178: recipe for target 'gunrock/CMakeFiles/gunrock.dir/all' failed
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
```
GPU: RTX 3060ti
CPU: AMD Ryzen 3950x
OS: Ubuntu 18.04.1 LTS
Driver Version: 516.59
CUDA Version: 11.7
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by crozhon** [comment] 2022-07-31 23:27
Thanks for reporting. We will take a look.

**Comment by sam0oneau** [comment] 2022-08-01 00:23
> Thanks for reporting. We will take a look.

No worries, as I mentioned I will take a look at https://github.com/gunrock/gunrock/issues/905#issuecomment-1025038876 tomorrow to see if that fixes, sadly didn't have time today. Hopefully dev branch fixes this.

**Comment by sam0oneau** [comment] 2022-08-01 13:03
Sadly it still fails to build on dev branch with the following:
```
sam0oneau@DESKTOP-3913TJA:~/GSM/gunrock/build$ make
[  0%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/archivertest.dir/archiver/archiver.cpp.o
[  0%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/archivertest.dir/archiver/archivertest.cpp.o
[  1%] Linking CXX executable ../../../bin/archivertest
[  1%] Built target archivertest
[  1%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o
[  1%] Linking CXX executable ../../../bin/capitalize
[  1%] Built target capitalize
[  2%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/condense.dir/condense/condense.cpp.o
[  2%] Linking CXX executable ../../../bin/condense
[  2%] Built target condense
[  3%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/filterkey.dir/filterkey/filterkey.cpp.o
[  3%] Linking CXX executable ../../../bin/filterkey
[  3%] Built target filterkey
[  3%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/filterkeydom.dir/filterkeydom/filterkeydom.cpp.o
[  4%] Linking CXX executable ../../../bin/filterkeydom
[  4%] Built target filterkeydom
[  5%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/jsonx.dir/jsonx/jsonx.cpp.o
[  5%] Linking CXX executable ../../../bin/jsonx
[  5%] Built target jsonx
[  6%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/lookaheadparser.dir/lookaheadparser/lookaheadparser.cpp.o
[  6%] Linking CXX executable ../../../bin/lookaheadparser
[  6%] Built target lookaheadparser
[  6%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/messagereader.dir/messagereader/messagereader.cpp.o
[  7%] Linking CXX executable ../../../bin/messagereader
[  7%] Built target messagereader
[  7%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/parsebyparts.dir/parsebyparts/parsebyparts.cpp.o
[  7%] Linking CXX executable ../../../bin/parsebyparts
[  7%] Built target parsebyparts
[  7%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/pretty.dir/pretty/pretty.cpp.o
[  7%] Linking CXX executable ../../../bin/pretty
[  7%] Built target pretty
[  8%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/prettyauto.dir/prettyauto/prettyauto.cpp.o
[  8%] Linking CXX executable ../../../bin/prettyauto
[  8%] Built target prettyauto
[  9%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/schemavalidator.dir/schemavalidator/schemavalidator.cpp.o
[  9%] Linking CXX executable ../../../bin/schemavalidator
[  9%] Built target schemavalidator
[  9%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/serialize.dir/serialize/serialize.cpp.o
[ 10%] Linking CXX executable ../../../bin/serialize
[ 10%] Built target serialize
[ 10%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/simpledom.dir/simpledom/simpledom.cpp.o
[ 10%] Linking CXX executable ../../../bin/simpledom
[ 10%] Built target simpledom
[ 11%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/simplereader.dir/simplereader/simplereader.cpp.o
[ 11%] Linking CXX executable ../../../bin/simplereader
[ 11%] Built target simplereader
[ 12%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/simplepullreader.dir/simplepullreader/simplepullreader.cpp.o
[ 12%] Linking CXX executable ../../../bin/simplepullreader
[ 12%] Built target simplepullreader
[ 12%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/simplewriter.dir/simplewriter/simplewriter.cpp.o
[ 13%] Linking CXX executable ../../../bin/simplewriter
[ 13%] Built target simplewriter
[ 13%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/sortkeys.dir/sortkeys/sortkeys.cpp.o
[ 13%] Linking CXX executable ../../../bin/sortkeys
[ 13%] Built target sortkeys
[ 13%] Building CXX object _deps/rapidjson-build/example/CMakeFiles/tutorial.dir/tutorial/tutorial.cpp.o
[ 13%] Linking CXX executable ../../../bin/tutorial
[ 13%] Built target tutorial
[ 13%] Built target examples
[ 13%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/namespacetest.dir/namespacetest.cpp.o
[ 14%] Linking CXX static library ../../../../lib/libnamespacetest.a
[ 14%] Built target namespacetest
[ 14%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 14%] Linking CXX static library ../lib/libgtest.a
[ 14%] Built target gtest
[ 15%] Building CXX object googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 15%] Linking CXX static library ../lib/libgtest_main.a
[ 15%] Built target gtest_main
[ 16%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/allocatorstest.cpp.o
[ 16%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/bigintegertest.cpp.o
[ 16%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/cursorstreamwrappertest.cpp.o
[ 17%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/documenttest.cpp.o
[ 17%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/dtoatest.cpp.o
[ 18%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/encodedstreamtest.cpp.o
[ 18%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/encodingstest.cpp.o
[ 18%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/fwdtest.cpp.o
[ 19%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/filestreamtest.cpp.o
[ 19%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/itoatest.cpp.o
[ 19%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/istreamwrappertest.cpp.o
[ 20%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/jsoncheckertest.cpp.o
[ 20%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/namespacetest.cpp.o
[ 21%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/pointertest.cpp.o
[ 21%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/prettywritertest.cpp.o
[ 21%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/ostreamwrappertest.cpp.o
[ 22%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/readertest.cpp.o
[ 22%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/regextest.cpp.o
[ 22%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/schematest.cpp.o
[ 23%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/simdtest.cpp.o
[ 23%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/strfunctest.cpp.o
[ 24%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/stringbuffertest.cpp.o
[ 24%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/strtodtest.cpp.o
[ 24%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/unittest.cpp.o
[ 25%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/valuetest.cpp.o
[ 25%] Building CXX object _deps/rapidjson-build/test/unittest/CMakeFiles/unittest.dir/writertest.cpp.o
[ 25%] Linking CXX executable ../../../../bin/unittest
[ 25%] Built target unittest
[ 26%] Building CXX object _deps/rapidjson-build/test/perftest/CMakeFiles/perftest.dir/misctest.cpp.o
[ 26%] Building CXX object _deps/rapidjson-build/test/perftest/CMakeFiles/perftest.dir/perftest.cpp.o
[ 26%] Building CXX object _deps/rapidjson-build/test/perftest/CMakeFiles/perftest.dir/platformtest.cpp.o
[ 27%] Building CXX object _deps/rapidjson-build/test/perftest/CMakeFiles/perftest.dir/rapidjsontest.cpp.o
[ 27%] Building CXX object _deps/rapidjson-build/test/perftest/CMakeFiles/perftest.dir/schematest.cpp.o
[ 28%] Linking CXX executable ../../../../bin/perftest
[ 28%] Built target perftest
[ 28%] Built target tests
[ 28%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/util/gunrock_generated_test_utils.cu.o
[ 28%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/hits/gunrock_generated_hits_app.cu.o
[ 29%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/pr/gunrock_generated_pr_app.cu.o
[ 30%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/sm/gunrock_generated_sm_app.cu.o
[ 30%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/sssp/gunrock_generated_sssp_app.cu.o
[ 30%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/util/gunrock_generated_str_to_T.cu.o
[ 31%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/util/gunrock_generated_error_utils.cu.o
[ 31%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/util/gunrock_generated_misc_utils.cu.o
[ 32%] Building NVCC intermediate link file gunrock/CMakeFiles/gunrock.dir/gunrock_intermediate_link.o
nvlink error   : Multiple definition of '_ZN7gunrock4util2io13ModifiedStoreILNS1_2st13CacheModifierE3EE2StI6ulong2EEvT_PS8_' in '/home/sam0oneau/GSM/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/hits/./gunrock_generated_hits_app.cu.o', first defined in '/home/sam0oneau/GSM/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/pr/./gunrock_generated_pr_app.cu.o'
.. <Many Nvlink errors> ..
nvlink error   : Multiple definition of '_ZN7gunrock4util2io12ModifiedLoadILNS1_2ld13CacheModifierE1EE2LdI5char1EEvRT_PS8_' in '/home/sam0oneau/GSM/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/hits/./gunrock_generated_hits_app.cu.o', first defined in '/home/sam0oneau/GSM/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/pr/./gunrock_generated_pr_app.cu.o'
nvlink error   : Multiple definition of '_ZN7gunrock4util2io12ModifiedLoadILNS1_2ld13CacheModifierE1EE2LdIcEEvRT_PS7_' in '/home/sam0oneau/GSM/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/hits/./gunrock_generated_hits_app.cu.o', first defined in '/home/sam0oneau/GSM/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/pr/./gunrock_generated_pr_app.cu.o'
nvlink error   : Multiple definition of '_ZN7gunrock4util2io12ModifiedLoadILNS1_2ld13CacheModifierE1EE2LdIiEEvRT_PS7_' in '/home/sam0oneau/GSM/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/hits/./gunrock_generated_hits_app.cu.o', first defined in '/home/sam0oneau/GSM/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/pr/./gunrock_generated_pr_app.cu.o'
nvlink error   : Multiple definition of '_ZN7gunrock4util2io13ModifiedStoreILNS1_2st13CacheModifierE1EE2StIiEEvT_PS7_' in '/home/sam0oneau/GSM/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/hits/./gunrock_generated_hits_app.cu.o', first defined in '/home/sam0oneau/GSM/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/pr/./gunrock_generated_pr_app.cu.o'
nvlink fatal   : merge_elf failed
gunrock/CMakeFiles/gunrock.dir/build.make:136: recipe for target 'gunrock/CMakeFiles/gunrock.dir/gunrock_intermediate_link.o' failed
make[2]: *** [gunrock/CMakeFiles/gunrock.dir/gunrock_intermediate_link.o] Error 1
CMakeFiles/Makefile2:2214: recipe for target 'gunrock/CMakeFiles/gunrock.dir/all' failed
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2```

gcc-9 (Ubuntu 9.4.0-1ubuntu1~18.04) 9.4.0
g++-9 (Ubuntu 9.4.0-1ubuntu1~18.04) 9.4.0
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

**Comment by sam0oneau** [comment] 2022-08-03 16:38
I presume this a dependency issue and possibly not Cuda 11.7 related?
I am all ears to ideas as I do want to profile GunrockSM soon. Worst case scenario, I may just ask someone who has it built already to me a working binary.

**Comment by sam0oneau** [comment] 2022-08-08 08:02
@crozhon Hello, I was hoping if you had any idea how I could move forward with this? I've still sadly been unable to get it to build, and all I really wanted to do was be able to benchmark "Fast Gunrock Subgraph Matching (GSM)" for various snap.stanford.edu datasets.

I don't know how portable it is, but would it be possible if you could send me a binary built for Turing (SM 75 Binary). If not, no worries, but it would be great if you had any ideas on how I could move forward with this.

This is not an issue, but I have noticed that the cmake is building a target for SM 70 not SM 86 (On Ampere). I believe that is because there is no SM 86 case in your cmake list (This shouldn't break anything though that it uses SM 70).

**Comment by crozhon** [comment] 2022-08-08 10:02
I think the issue is likely related to the CUDA version. I believe SM_75 and CUDA 11.2 are the limits of what we've built Gunrock with. 

If all you care about is subgraph matching, it could help to comment out the other applications in CMakeLists.txt. It looks like the issue comes from building multiple targets, so if you only need SM you might be able to sidestep it. It's likely some included CUB function is getting defined multiple times. Try only building the SM app or find out where we mistakenly redefine it (probably somewhere in util/).

@neoblizz might also have a solution for you depending on what you need. 

I'll dig around for a prebuilt SM_75 binary. We might have one lying around, but I think it's unlikely.

**Comment by sam0oneau** [comment] 2022-08-08 10:50
> I think the issue is likely related to the CUDA version. I believe SM_75 and CUDA 11.2 are the limits of what we've built Gunrock with.
> 
> If all you care about is subgraph matching, it could help to comment out the other applications in CMakeLists.txt. It looks like the issue comes from building multiple targets, so if you only need SM you might be able to sidestep it. It's likely some included CUB function is getting defined multiple times. Try only building the SM app or find out where we mistakenly redefine it (probably somewhere in util/).
> 
> @neoblizz might also have a solution for you depending on what you need.
> 
> I'll dig around for a prebuilt SM_75 binary. We might have one lying around, but I think it's unlikely.

I a

**Comment by sam0oneau** [comment] 2022-08-08 10:52
> I think the issue is likely related to the CUDA version. I believe SM_75 and CUDA 11.2 are the limits of what we've built Gunrock with.
> 
> If all you care about is subgraph matching, it could help to comment out the other applications in CMakeLists.txt. It looks like the issue comes from building multiple targets, so if you only need SM you might be able to sidestep it. It's likely some included CUB function is getting defined multiple times. Try only building the SM app or find out where we mistakenly redefine it (probably somewhere in util/).
> 
> @neoblizz might also have a solution for you depending on what you need.
> 
> I'll dig around for a prebuilt SM_75 binary. We might have one lying around, but I think it's unlikely.

Thank you, I’ll take a look at this tonight. I appreciate you taking the time to help.  Apologies about that mistake with closing the issue I misclicked.

**Comment by crozhon** [comment] 2022-08-09 11:15
Build should be fixed on dev. Thanks for reporting this.

**Comment by sam0oneau** [comment] 2022-08-09 11:59
> Build should be fixed on dev. Thanks for reporting this.

Thank you for taking a look at this, this is very helpful. I’ll take check out dev build later today or tomorrow. I’m looking forward to seeing how GunrockSM performs.

**Comment by jowens** [comment] 2022-08-09 14:56
@crozhon you are a tremendous human being and future generations will marvel at your munificence

**Comment by sam0oneau** [comment] 2022-08-10 10:50
> Build should be fixed on dev. Thanks for reporting this.

It now builds (and builds quite fast compared to before). I look forward to running benchmarks on GunrockSM this week, hopefully it behaves on Ampere and Turing (fingers crossed). I will mark this as closed, hopefully no more issues from here on out. Thank you John Owens and Chuck Rozhon for the help on working with GunrockSM.

**Closed** 2022-08-10 10:50 UTC
Labels: bug
