### ISSUE TITLE
BC cTest failed intermittent on GV100

### ISSUE THREAD

**Issue by hugovbraun** [gunrock/gunrock#359] opened 2018-07-13 12:50 UTC
We've been noticing some intermittent tests failure with GV100. Here's the details : 

*Description:*

When run Gunrock testing,cTest will failed intermittent on GV100.
This issue exist with CUDA 9.2.148 + DRIVER 396.37,CUDA 9.1.85 and CUDA 9.0.176.
The failed test case:
          8 - SHARED_LIB_TEST_BC (Failed)
          2 - TEST_BC (Failed)

Notes:
On Titan V no such issue.

Detail test log :

[ctest.6.log.txt](https://github.com/gunrock/gunrock/files/2192665/ctest.6.log.txt)
[ctest.9.log.txt](https://github.com/gunrock/gunrock/files/2192666/ctest.9.log.txt)
[summary.log.txt](https://github.com/gunrock/gunrock/files/2192667/summary.log.txt)

**Comment by Hugovb7** [comment] 2018-09-14 18:28
Attached are the logs with driver 410 : 
[Run_Gunrock.zip](https://github.com/gunrock/gunrock/files/2384510/Run_Gunrock.zip)

**Comment by Hugovb7** [comment] 2018-09-24 20:09
Were you guys able to reproduce this bug ?

**Comment by neoblizz** [comment] 2018-10-14 04:41
Haven't gotten a chance to work on this bug, this has been pushed to after November 1st (we have some deadlines till then). Didn't forget, will see if I can address this after 1st.

**Comment by neoblizz** [comment] 2019-02-17 15:54
Unable to reproduce this on a 100 runs on different configs, I am assuming this is fixed in 410.72 (I don't get this on past drivers as well).

**Closed by neoblizz** 2019-02-17 15:54 UTC
Labels: bug
