### ISSUE TITLE
Issues reproducing performance tests on Volta system.

### ISSUE THREAD

**Issue by jwyles** [gunrock/gunrock#324] opened 2018-03-07 16:50 UTC
I am trying to run some benchmark results on a DGX  Volta system, but am running across the following problems:

1. Matrix Market format input does not appear to work. When using the .MTX files downloaded via Makefile in /dataset/large, the pr and bfs executables crash with a segfault reading in the file:
```
build/bin/bfs market dataset/large/hollywood-2009/hollywood-2009.mtx
Loading Matrix-market coordinate-formatted graph ...
Segmentation fault (core dumped)
```

2. The pr executable hangs (given rmat generated graph as input):
```
build/bin/pr rmat
Generating R-MAT graph ...
rmat_seed = 1520441285
  Converting 1024 vertices, 98304 directed edges (unordered tuples) to CSR format...
Done converting (0s).
R-MAT graph generated in 78.617 ms, a = 0.570, b = 0.190, c = 0.190, d = 0.050

Degree Histogram (1024 vertices, 47436 edges):
    Degree   0: 49 (4.79%)
    Degree 2^0: 52 (5.08%)
    Degree 2^1: 81 (7.91%)
    Degree 2^2: 141 (13.77%)
    Degree 2^3: 135 (13.18%)
    Degree 2^4: 180 (17.58%)
    Degree 2^5: 206 (20.12%)
    Degree 2^6: 101 (9.86%)
    Degree 2^7: 49 (4.79%)
    Degree 2^8: 29 (2.83%)
    Degree 2^9: 1 (0.10%)

Using 1 GPU: [ 0 ].
Using traversal mode LB
-1	 -1	 -1	 scanned_edges 	 oversize :	 2 ->	 1026
__________________________

```

**Comment by jowens** [comment] 2018-03-07 16:58
Please tell us what OS, compiler version, CUDA version, and GPU you're using.

1. Can you give us a command-line you're running?
2. We're actively working on this (@neoblizz went back to patch up all the cooperative-groups-sync kind of code, but Volta still doesn't work for us). We're as eager to fix this as you are.

**Comment by jwyles** [comment] 2018-03-07 17:03
OS: Ubuntu 16.04
Compiler Version: GCC 4.8
CUDA version: 9.1
GPU: Quadro GV100

Note: The bfs executable does run through fine when using a generated rmat graph.

**Comment by jwyles** [comment] 2018-03-07 17:14
Any thoughts on the issue with reading in .MTX files? Is there something I am missing something there?

**Comment by jowens** [comment] 2018-03-07 17:15
Please give us your command-line ...

**Comment by sgpyc** [comment] 2018-03-07 17:17
I don't think the mtx issue is Volta related, since the part that crashed is purely CPU code.
Will try to reproduce the bug on our machine using @jwyles's command line

**Comment by sgpyc** [comment] 2018-03-07 17:20
By the way, can @jwyles try `ls -lart` in the directory containing the .mtx file?
The mtx reader will try to store a binary version of the file, and it's hidden.

**Comment by jwyles** [comment] 2018-03-07 17:22
```
~/Gunrock/gunrock/dataset/large/hollywood-2009$ ls -lart
total 945588
-rw-rw-r--  1 jwyles jwyles 159474427 Mar  7  2015 hollywood-2009.tar.gz
-rwxrwxr-x  1 jwyles jwyles       149 Mar  5 14:31 Makefile
drwxrwxr-x 28 jwyles jwyles      4096 Mar  5 14:31 ..
-rw-------  1 jwyles jwyles 808787923 Mar  6 10:52 hollywood-2009.mtx
drwxrwxr-x  2 jwyles jwyles      4096 Mar  6 10:52 .
```

**Comment by neoblizz** [comment] 2018-03-07 17:26
For problem 2) you could downgrade to CUDA 9 or CUDA 8, they seem to work with Voltas. This is a bug in CUDA 9.1 + Volta.

**Comment by jwyles** [comment] 2018-03-07 17:39
John,

The command lines I used are in the Github issue examples.

Cheers,

James

**Comment by jowens** [comment] 2018-03-07 17:40
Oh sorry. You're right.

**Comment by jwyles** [comment] 2018-03-07 18:25
I tried downgrading CUDA to 9.0, but still get the same hanging issue with pr.

**Comment by sgpyc** [comment] 2018-03-07 22:44
I can't reproduce the mtx issue, on top of the master branch, with or without the stored binary version of hollywood-2009.mtx. I noticed @jwyles 's gcc is 4.8, but the supported version should be at least 5.3.1 (http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html).

My environment is: ubuntu 16.04 + GCC 5.4.0 + NVCC 9.1.85 + NVIDIA Driver 390.30, Titan V.

**Comment by jwyles** [comment] 2018-03-08 18:39
running ctest -vv:
```
ctest -vv
Test project /home/jwyles/Gunrock/gunrock/build
      Start  1: TEST_BFS
 1/11 Test  #1: TEST_BFS .........................***Exception: SegFault  0.12 sec
      Start  2: TEST_BC
 2/11 Test  #2: TEST_BC ..........................***Exception: SegFault  0.12 sec
      Start  3: TEST_CC
 3/11 Test  #3: TEST_CC ..........................***Exception: SegFault  0.11 sec
      Start  4: TEST_SSSP
 4/11 Test  #4: TEST_SSSP ........................***Exception: SegFault  0.11 sec
      Start  5: TEST_PAGERANK
```

And there it appears to hang up.

**Comment by jwyles** [comment] 2018-03-08 19:59
Re-compiling with GCC 5.4 fixed the issue with the segfaults while loading matrix market files. Still seeing hanging in pr and cc executables.

**Comment by neoblizz** [comment] 2018-03-08 21:37
@jwyles does it hang with CUDA 8 as well? I am not a 100% sure if the CUDA 9.1 + Volta bug is only in CUDA 9.1 or in 9 as well. @sgpyc can you comment on this?

**Comment by sgpyc** [comment] 2018-03-09 11:28
The hanging is the same as Issue #312, and can be reproduced by the attached code.
Any kernel using BlockScan or WarpScan routines will hit the same bug.
I think it's a bug in CUDA 9.1 itself. 

```
#include <iostream>
#include <stdio.h>

using namespace std;

__global__
void shfl_kernel(int *d_elements)
{
    __syncthreads();
    int lane_id = threadIdx.x & 0x1f;
    int lane_local = lane_id;
    int lane_recv = lane_id + 32; 

    if ((lane_id & 0xfu) == 0)
    {   
        lane_local += lane_recv;
        lane_recv = __shfl_xor_sync(0x00010001u, lane_local, 0x10u);
    }   
    // __syncthreads(); // this is the workaround

    lane_local = lane_recv; // this line causes hang
   
    lane_recv = __shfl_up_sync(0xffffffffu, lane_local, 8); 
    __syncthreads();
    d_elements[threadIdx.x] = lane_recv;
}

int main()
{
    int num_elements = 32; // 1024;
    int *d_elements = NULL;
    cudaMalloc(&d_elements, sizeof(int) * num_elements);
    int *h_elements = new int[num_elements];
        
    shfl_kernel<<<1, num_elements>>>(d_elements);
    cudaMemcpy(h_elements, d_elements, sizeof(int) * num_elements, cudaMemcpyDeviceToHost);

    int group_size = 32; 
    for (int i = 0; i < num_elements; i++)
    {
        if ((i % group_size) == 0) cout << endl << "|(" << i << ") ";
        cout << h_elements[i];
        if ((i % group_size) != group_size-1 && i != num_elements -1) cout << ", ";
    }   
    cudaFree(d_elements); d_elements = NULL;
    delete[] h_elements; h_elements = NULL;
    return 0;
}
```

**Comment by jowens** [comment] 2018-03-09 14:59
Should we loop Nikolai and/or Duane into this conversation?

Does the extra `__syncthreads()` solve the problem in Gunrock (do you have to do this in the scan routines we're using)?

**Comment by sgpyc** [comment] 2018-03-10 22:12
The current solution is to add `__all_sync(0xffffffffu, 1);` to sync all threads within a warp.
My guess is doing shuffle on lane 0 & 16 within a if statement some how messes up the internal active thread mask.

The WarpScan is mainly used to compute input and output positions. Other places we mainly use Scan routines from cub, which work fine. 
I think Duane may know what went wrong.

**Comment by jowens** [comment] 2018-03-10 22:35
@dumerrill

**Comment by jowens** [comment] 2018-03-12 00:03
@nsakharnykh consider taking a peek at this and the workaround below?

https://github.com/gunrock/gunrock/pull/325

**Comment by sgpyc** [comment] 2018-03-12 08:49
I filed a bug report (2080669) via the NVIDIA developer program.
It has been reproduced, and I will post updates when available.

**Comment by jowens** [comment] 2018-03-12 17:22
you the man @sgpyc

**Comment by nsakharnykh** [comment] 2018-03-13 03:36
Thanks for filing the bug, this is usually the right way to do it :) and I'm sorry I couldn't look at this any time soon - very busy up until GTC as usual. Hopefully the engineers assigned to the bug can find some time to look into this before I do.

**Comment by jowens** [comment] 2018-03-13 04:55
Thanks @nsakharnykh -- you're always on our side, much appreciated. Good luck with your GTC projects!

**Comment by neoblizz** [comment] 2019-02-17 15:59
I believe this issue was resolved in later driver and CUDA updates, unable to reproduce this with the latest toolkit.

**Closed by neoblizz** 2019-02-17 15:59 UTC
Labels: bug
