### ISSUE TITLE
PageRank Multi-GPU Errors

### ISSUE THREAD

**Issue by tbennun** [gunrock/gunrock#191] opened 2016-09-18 06:41 UTC
Tested on v0.3.1 and master (07af4a1adc6c9226e9010b65d5e3afadb09a6df1).

Running PageRank on multiple GPUs produces comparison errors (compared to external results and internal Gunrock CPU regression) on multiple graphs.

The error becomes worse (on average) as the number of GPUs increases, and the ranking order changes.

Can be reproduced using the following commands:
`./pagerank rmat --rmat_seed=1234 --device=0`

```
Generating R-MAT graph ...
rmat_seed = 1234
  Converting 1024 vertices, 98304 directed edges (unordered tuples) to CSR format...
Done converting (0s).
R-MAT graph generated in 46.754 ms, a = 0.570, b = 0.190, c = 0.190, d = 0.050
----- snip -----
Validity Rank:
INCORRECT: [1022]: 0.1500000.000000
result[...0.150000, 0.150000, 0.150000, 0.150000, 0.150000, 0.150000, 0.150000, ...]
reference[...0.150000, 0.150000, 0.150000, 0.150000, 0.150000, 0.000000, 0.000000, ...]
number of errors : 3

First 40 labels of the GPU result.
Top 10 Ranked Vertices and PageRanks:
Vertex ID: 0, PageRank: 14.609468
Vertex ID: 1, PageRank: 9.269779
Vertex ID: 64, PageRank: 9.145162
Vertex ID: 256, PageRank: 9.095755
Vertex ID: 4, PageRank: 9.027366
Vertex ID: 8, PageRank: 8.642411
Vertex ID: 512, PageRank: 8.640956
Vertex ID: 16, PageRank: 8.544449
Vertex ID: 32, PageRank: 8.536005
Vertex ID: 128, PageRank: 8.239375
```

`./pagerank rmat --rmat_seed=1234 --device=0,1`

```
----- snip -----
Validity Rank:
INCORRECT: [625]: 0.3401900.358223
result[...0.345215, 0.343489, 0.342870, 0.342740, 0.341754, 0.340190, 0.340171, 0.340030, 0.339305, 0.338982, ...]
reference[...0.361065, 0.359982, 0.359801, 0.359667, 0.358485, 0.358223, 0.357556, 0.357396, 0.357077, 0.356100, ...]
number of errors : 29

First 40 labels of the GPU result.
Top 10 Ranked Vertices and PageRanks:
Vertex ID: 0, PageRank: 14.170243
Vertex ID: 4, PageRank: 9.109018
Vertex ID: 64, PageRank: 9.076447
Vertex ID: 1, PageRank: 9.062875
Vertex ID: 256, PageRank: 9.036615
Vertex ID: 8, PageRank: 8.658578
Vertex ID: 512, PageRank: 8.553918
Vertex ID: 16, PageRank: 8.502898
Vertex ID: 32, PageRank: 8.501092
Vertex ID: 128, PageRank: 8.223996
```

`./pagerank rmat --rmat_seed=1234 --device=0,1,2,3`

```
----- snip -----
Validity Rank:
INCORRECT: [375]: 0.7631530.812625
result[...0.797909, 0.793867, 0.786783, 0.786331, 0.776090, 0.763153, 0.759018, 0.756434, 0.755855, 0.746385, ...]
reference[...0.824505, 0.824476, 0.821139, 0.814037, 0.813029, 0.812625, 0.803317, 0.802732, 0.801525, 0.798488, ...]
number of errors : 234

First 40 labels of the GPU result.
Top 10 Ranked Vertices and PageRanks:
Vertex ID: 0, PageRank: 14.150754
Vertex ID: 256, PageRank: 9.135432
Vertex ID: 64, PageRank: 9.127813
Vertex ID: 1, PageRank: 9.117531
Vertex ID: 4, PageRank: 8.864873
Vertex ID: 16, PageRank: 8.639098
Vertex ID: 8, PageRank: 8.638387
Vertex ID: 512, PageRank: 8.599026
Vertex ID: 32, PageRank: 8.563516
Vertex ID: 128, PageRank: 8.298841
```

**Comment by tbennun** [comment] 2016-09-18 06:46
Also attaching simple matrix market that reproduces the problem.
[sample.mtx.txt](https://github.com/gunrock/gunrock/files/478561/sample.mtx.txt)

Outputs:

1 GPU:
```
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (0s).

Degree Histogram (5 vertices, 6 edges):
    Degree   0: 1 (20.00%)
    Degree 2^0: 3 (60.00%)
    Degree 2^1: 1 (20.00%)

Using 1 GPU(s): [ 0 ].
__________________________
--------------------------
Total rank : 3.973282
Computing reference value ...
CPU PageRank finished in 0.118971 msec.

Validity Rank:
CORRECT
First 40 labels of the GPU result.
Top 5 Ranked Vertices and PageRanks:
Vertex ID: 3, PageRank: 1.825443
Vertex ID: 0, PageRank: 0.665946
Vertex ID: 1, PageRank: 0.665946
Vertex ID: 4, PageRank: 0.665946
Vertex ID: 2, PageRank: 0.150000

 [PageRank] finished.
 elapsed: 3.3941 ms
 iterations: 18
 edges queued: 193
 edges redundance: 3116.67%

        Memory Usage(B)  #keys0,0        #keys0,1
GPU_0    2097152         8       8
         queue_sizing =  1.600000        1.600000
```


2 GPUs:
```
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (0s).

Degree Histogram (5 vertices, 6 edges):
    Degree   0: 1 (20.00%)
    Degree 2^0: 3 (60.00%)
    Degree 2^1: 1 (20.00%)

Using 2 GPU(s): [ 0 1 ].
__________________________
--------------------------
Total rank : 0.920000
Computing reference value ...
CPU PageRank finished in 0.120163 msec.

Validity Rank:
INCORRECT: [0]: 0.2350001.918411
result[...0.235000, 0.192500, 0.192500, 0.150000, 0.150000, ...]
reference[...1.918411, 0.693548, 0.693548, 0.693548, 0.150000, ...]
number of errors : 5

First 40 labels of the GPU result.
Top 5 Ranked Vertices and PageRanks:
Vertex ID: 4, PageRank: 0.235000
Vertex ID: 0, PageRank: 0.192500
Vertex ID: 1, PageRank: 0.192500
Vertex ID: 2, PageRank: 0.150000
Vertex ID: 3, PageRank: 0.150000

 [PageRank] finished.
 elapsed: 4.7350 ms
 iterations: 6
 edges queued: 34
 edges redundance: 466.67%

        Memory Usage(B)  #keys0,0        #keys0,1 #keys1,0       #keys1,1        #ins1,0         #ins1,1 #keys2
GPU_0    2105344         4       4       3       3       3       3       6
GPU_1    2097152         6       6       3       3       3       3       6
         queue_sizing =  2.000000        2.000000        in_sizing =     1.000000
```

**Comment by jowens** [comment] 2016-09-18 19:01
Just to be clear, the problem is with multiple GPUs but not one GPU? Certainly these are bugs we're cleaning up in preparation for a 0.4 release. Thank you for reporting it! The Gunrock team is in DC this week so response might be slow, but I'm assigning to @sgpyc since he's leading the multi-GPU work.

**Comment by tbennun** [comment] 2016-09-18 20:38
Thank you for the prompt response.

The single GPU version seems to be producing acceptable results, especially in small graphs. The multi-GPU version, however, fails for all the cases I tested.

**Comment by sgpyc** [comment] 2016-09-18 21:34
My guess of the course is some parameter settings or graph type mismatch. Will check whether the latest pre-release branch fix that.

**Comment by sgpyc** [comment] 2016-10-03 23:39
Just tested PR on top of pre-release branch, a few things here:
1. --normalized option is added to make sure the sum of ranking values converging to 1
2. --compensate option is added to deal with "the ranking values vanish from 0 out degree vertices" issue
with "--normalized --compensate" in command line parameters, the ranking values and the vertex orders should be correct or close enough (look at the "maximum difference" and the "maximum relative difference" when ranking validation reports "INCORRECT").

For the sample.mtx.txt file, it contains self-loops (vertices having edges pointing to themselves). The mtx reading routine in Gunrock removes duplicated edges and self-loops. The number of edges reduces from 8 to 3 after this process. It may be the cause of comparison errors when comparing to external libraries. We can add flags to enable duplicated edges and self-loops, if they are required.

The outputs of related PR runs:
rmat on single GPU:
```
./bin/test_pr_8.0_x86_64 rmat --rmat_seed=1234 --device=0 --normalized --compensate
Generating R-MAT graph ...
rmat_seed = 1234
  Converting 1024 vertices, 49152 directed edges (unordered tuples) to CSR format...
Done converting (0s).
R-MAT graph generated in 46.735 ms, a = 0.570, b = 0.190, c = 0.190, d = 0.050

Degree Histogram (1024 vertices, 28631 edges):
    Degree   0: 112 (10.94%)
    Degree 2^0: 72 (7.03%)
    Degree 2^1: 115 (11.23%)
    Degree 2^2: 148 (14.45%)
    Degree 2^3: 189 (18.46%)
    Degree 2^4: 176 (17.19%)
    Degree 2^5: 49 (4.79%)
    Degree 2^6: 107 (10.45%)
    Degree 2^7: 45 (4.39%)
    Degree 2^8: 10 (0.98%)
    Degree 2^9: 1 (0.10%)

Using 1 GPU(s): [ 0 ].
Adding 1 vertex and 1136 edges to compensate 0 degree vertices
Using traversal mode LB
-1	 -1	 -1	 scanned_edges 	 oversize :	 2 ->	 1027
__________________________
--------------------------
iteration 0 elapsed: 1.016140 ms
Total rank : 0.9999999691
Computing reference value ...
CPU iteration : 7
CPU PageRank finished in 81.185104 msec.

Validity Rank: 
CORRECT
Reference total rank : 1.0000000617
Maximum difference : rank[0] 1.88349523e-02 vs. 1.88349616e-02, 9.31322575e-09
Maximum relative difference :rank[257] 4.71271481e-03 vs. 4.71271854e-03, 0.00007905 %
Validity Order: 
CORRECT

Top 10 Ranked Vertices and PageRanks:
Vertex ID: 0, PageRank: 1.88349523e-02
Vertex ID: 1024, PageRank: 1.83532145e-02
Vertex ID: 128, PageRank: 1.11040715e-02
Vertex ID: 8, PageRank: 1.09350011e-02
Vertex ID: 1, PageRank: 1.05560319e-02
Vertex ID: 256, PageRank: 1.00953318e-02
Vertex ID: 32, PageRank: 1.00566037e-02
Vertex ID: 64, PageRank: 9.96408332e-03
Vertex ID: 512, PageRank: 9.95559711e-03
Vertex ID: 4, PageRank: 9.83467139e-03

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_0	 5242880	 2	 2
	 queue_sizing =	 0.001951 	 0.001951

 [PageRank] finished.
 avg. elapsed: 1.0161 ms
 iterations: 8
 min. elapsed: 1.0161 ms
 max. elapsed: 1.0161 ms
 rate: 29.2942 MiEdges/s
 src: 0
 nodes_visited: 1025
 edges_visited: 29767
 nodes queued: 7175
 edges queued: 238136
 nodes redundance: 600.00%
 edges redundance: 700.00%
 load time: 645.0191 ms
 preprocess time: 6.3632 ms
 postprocess time: 90.7431 ms
 total time: 743.5338 ms
```

rmat on 4 GPUs
```
./bin/test_pr_8.0_x86_64 rmat --rmat_seed=1234 --device=0,1,2,3 --normalized --compensate 
Generating R-MAT graph ...
rmat_seed = 1234
  Converting 1024 vertices, 49152 directed edges (unordered tuples) to CSR format...
Done converting (0s).
R-MAT graph generated in 52.783 ms, a = 0.570, b = 0.190, c = 0.190, d = 0.050

Degree Histogram (1024 vertices, 28631 edges):
    Degree   0: 112 (10.94%)
    Degree 2^0: 72 (7.03%)
    Degree 2^1: 115 (11.23%)
    Degree 2^2: 148 (14.45%)
    Degree 2^3: 189 (18.46%)
    Degree 2^4: 176 (17.19%)
    Degree 2^5: 49 (4.79%)
    Degree 2^6: 107 (10.45%)
    Degree 2^7: 45 (4.39%)
    Degree 2^8: 10 (0.98%)
    Degree 2^9: 1 (0.10%)

Using 4 GPU(s): [ 0 1 2 3 ].
Adding 1 vertex and 1136 edges to compensate 0 degree vertices
Partition begin. seed=1475537792
partition end. (3.879070 ms)
Using traversal mode LB
-1	 -1	 -1	 scanned_edges 	 oversize :	 2 ->	 258
-1	 -1	 -1	 scanned_edges 	 oversize :	 2 ->	 258
-1	 -1	 -1	 scanned_edges 	 oversize :	 2 ->	 258
-1	 -1	 -1	 scanned_edges 	 oversize :	 2 ->	 259
__________________________
--------------------------
iteration 0 elapsed: 4.140854 ms
Total rank : 0.9999999664
Computing reference value ...
CPU iteration : 7
CPU PageRank finished in 65.687897 msec.

Validity Rank: 
CORRECT
Reference total rank : 0.9999999483
Maximum difference : rank[128] 1.11040715e-02 vs. 1.11040613e-02, 1.02445483e-08
Maximum relative difference :rank[128] 1.11040715e-02 vs. 1.11040613e-02, 0.00009226 %
Validity Order: 
CORRECT

Top 10 Ranked Vertices and PageRanks:
Vertex ID: 0, PageRank: 1.88349560e-02
Vertex ID: 1024, PageRank: 1.83532033e-02
Vertex ID: 128, PageRank: 1.11040715e-02
Vertex ID: 8, PageRank: 1.09350011e-02
Vertex ID: 1, PageRank: 1.05560282e-02
Vertex ID: 256, PageRank: 1.00953272e-02
Vertex ID: 32, PageRank: 1.00566009e-02
Vertex ID: 64, PageRank: 9.96407960e-03
Vertex ID: 512, PageRank: 9.95559618e-03
Vertex ID: 4, PageRank: 9.83467326e-03

	Memory Usage(B)	 #keys0,0	 #keys0,1 #keys1,0	 #keys1,1	 #ins1,0	 #ins1,1 #keys2,0	 #keys2,1	 #ins2,0	 #ins2,1 #keys3,0	 #keys3,1	 #ins3,0	 #ins3,1 #keys4
GPU_0	 5242880	 2	 2	 2	 2	 0	 0	 2	 2	 0	 0	 2	 2	 0	 0	 2
GPU_1	 5242880	 2	 2	 2	 2	 0	 0	 2	 2	 0	 0	 2	 2	 0	 0	 2
GPU_2	 5242880	 2	 2	 2	 2	 0	 0	 2	 2	 0	 0	 2	 2	 0	 0	 2
GPU_3	 5242880	 2	 2	 2	 2	 0	 0	 2	 2	 0	 0	 2	 2	 0	 0	 2
	 queue_sizing =	 0.011494 	 0.011494	 in_sizing =	 0.000000

 [PageRank] finished.
 avg. elapsed: 4.1409 ms
 iterations: 8
 min. elapsed: 4.1409 ms
 max. elapsed: 4.1409 ms
 rate: 7.1886 MiEdges/s
 src: 0
 nodes_visited: 1025
 edges_visited: 29767
 nodes queued: 7175
 edges queued: 238136
 nodes redundance: 600.00%
 edges redundance: 700.00%
 load time: 1443.4860 ms
 preprocess time: 63.5459 ms
 postprocess time: 108.0542 ms
 total time: 1622.1650 ms
```

sample.mtx on single GPU
```
./bin/test_pr_8.0_x86_64 market ./test_pr.mtx --normalized --compensate --device=0
Loading Matrix-market coordinate-formatted graph ...
Reading from ./test_pr.mtx:
  Parsing MARKET COO format (6 nodes, 8 directed edges)... Done parsing (0s).
  Converting 6 vertices, 8 directed edges (unordered tuples) to CSR format...
Done converting (0s).

Degree Histogram (6 vertices, 3 edges):
    Degree   0: 4 (66.67%)
    Degree 2^0: 1 (16.67%)
    Degree 2^1: 1 (16.67%)

Using 1 GPU(s): [ 0 ].
Adding 1 vertex and 10 edges to compensate 0 degree vertices
Using traversal mode TWC
__________________________
--------------------------
iteration 0 elapsed: 2.284050 ms
Total rank : 1.0000000969
Computing reference value ...
CPU iteration : 15
CPU PageRank finished in 125.200989 msec.

Validity Rank: 
CORRECT
Reference total rank : 0.9999999776
Maximum difference : rank[6] 3.75057995e-01 vs. 3.75057906e-01, 8.94069672e-08
Maximum relative difference :rank[6] 3.75057995e-01 vs. 3.75057906e-01, 0.00002384 %
Validity Order: 
CORRECT

Top 7 Ranked Vertices and PageRanks:
Vertex ID: 6, PageRank: 3.75057995e-01
Vertex ID: 3, PageRank: 1.37627199e-01
Vertex ID: 1, PageRank: 1.32525519e-01
Vertex ID: 4, PageRank: 1.32525519e-01
Vertex ID: 0, PageRank: 7.40879551e-02
Vertex ID: 2, PageRank: 7.40879551e-02
Vertex ID: 5, PageRank: 7.40879551e-02

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_0	 4194304	 2	 2
	 queue_sizing =	 0.285714 	 0.285714

 [PageRank] finished.
 avg. elapsed: 2.2840 ms
 iterations: 16
 min. elapsed: 2.2840 ms
 max. elapsed: 2.2840 ms
 src: 0
 nodes_visited: 7
 edges_visited: 13
 nodes queued: 105
 edges queued: 208
 nodes redundance: 1400.00%
 edges redundance: 1500.00%
 load time: 629.3850 ms
 preprocess time: 5.9040 ms
 postprocess time: 135.8049 ms
 total time: 773.6850 ms
```

**Comment by neoblizz** [comment] 2017-06-29 18:18
https://github.com/gunrock/gunrock/issues/243#issuecomment-301270446 please report back if you still encounter errors, I will reopen the issue.

**Closed by neoblizz** 2017-06-29 18:18 UTC
