### ISSUE TITLE
need eyeballs on GTX 1080 failure on midas

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#185] opened 2016-09-12 23:47 UTC
5 tests failed. It seems like lots is wrong here, so I'm surprised any succeeded, actually. @yzhwang, happy to have your input, but I'm assigning to @neoblizz, who can hopefully repro on midas.
[61.txt](https://github.com/gunrock/gunrock/files/468560/61.txt)

**Comment by jowens** [comment] 2016-09-12 23:48
It appears that even when we get the wrong result, we pass some regexps, which is a separate issue, which I'll open now.

**Comment by sgpyc** [comment] 2016-09-13 00:41
I tested using a GTX1070 on centOS 7 with CUDA 8.0, and most tests passed (except the one mentioned for the SSSP shared library). So it's most-likely a configuration / setup issue, rather than a actual bug. I remember midas has two GPUs, the older one (Tesla Cxxxx? with compute capability < 3.0) may not be able to run gunrock at all.

**Comment by jowens** [comment] 2016-09-13 01:08
I wasn't building 6.1 correctly. Hopefully this is better. Now they're all failing.

[61-2ndtry.txt](https://github.com/gunrock/gunrock/files/468644/61-2ndtry.txt)

**Comment by yzhwang** [comment] 2016-09-13 01:10
Hi @sgpyc I've fixed the shared lib sssp bug. Could you do a thorough test (run run.sh, run_real.sh, and run_rmat.sh) to make sure that there is no errors for large datasets?

**Comment by yzhwang** [comment] 2016-09-13 01:12
@jowens Sorry I might have missed the context, but what do you mean by 6.1?

**Comment by sgpyc** [comment] 2016-09-13 01:12
I'm running the tests, but that takes time

**Comment by jowens** [comment] 2016-09-13 01:13
Compute capability 6.1, which matches the GTX 1080 in midas AFAIK.

**Comment by yzhwang** [comment] 2016-09-13 01:13
@sgpyc Awesome! Thank you!

**Comment by sgpyc** [comment] 2016-09-13 01:21
the "unknown CUDA error" from problem::Init normally means the GPU it runs on is not compatible. Is it possible that the GTX 1080 is device 1 not 0? which means "--device=1" need to input as a command line argument, but I don't know whether the app / shared-library version support this or not.

**Comment by jowens** [comment] 2016-09-13 01:21
It's device 0.

```
$ /usr/local/cuda/samples/1_Utilities/deviceQuery/deviceQuery
/usr/local/cuda/samples/1_Utilities/deviceQuery/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 2 CUDA Capable device(s)

Device 0: "GeForce GTX 1080"
  CUDA Driver Version / Runtime Version          8.0 / 8.0
  CUDA Capability Major/Minor version number:    6.1
```

**Comment by neoblizz** [comment] 2016-09-13 01:36
@sgpyc what compute capability are you compiling for on your GTX 1070?

**Comment by sgpyc** [comment] 2016-09-13 01:39
I think 35, as what's stated in the CMakeLists.txt under pre-release branch. I can add 61 to see what will happened

**Comment by neoblizz** [comment] 2016-09-13 01:40
I will try it out. Can you also post your config settings here (output of cmake ..)? Thanks!

**Comment by sgpyc** [comment] 2016-09-13 01:48
Changed to 61, it works as before.

my output of cmake:
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found CUDA: /usr/local/cuda-8.0 (found suitable version "8.0", minimum required is "7.5") 
-- Boost version: 1.61.0
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found OpenMP
-- Found Metis
-- Project Added: bc
-- Project Added: bfs
-- Project Added: cc
-- Project Added: pr
-- Project Added: sssp
-- Project Added: hits
-- Project Added: salsa
-- Project Added: wtf
-- Project Added: topk
-- Configuring done
-- Generating done
-- Build files have been written to: /data/sgpyc/Projects/gunrock_build

**Comment by neoblizz** [comment] 2016-09-13 01:50
I have the same configs;
```
mosama@midas:~/research/gunrock/build$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "7.5") 
-- Boost version: 1.61.0
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found OpenMP
-- Found Metis
-- Project Added: bc
-- Project Added: bfs
-- Project Added: cc
-- Project Added: pr
-- Project Added: sssp
-- Project Added: hits
-- Project Added: salsa
-- Project Added: wtf
-- Project Added: topk
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mosama/research/gunrock/build
```

I don't think it can even access 1080 properly, the init fails;

```
Test project /home/mosama/research/gunrock/build
      Start  1: TEST_BFS
 1/11 Test  #1: TEST_BFS .........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.64 sec
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (0s).

Degree Histogram (7135 vertices, 30380 edges):
    Degree   0: 541 (7.58%)
    Degree 2^0: 626 (8.77%)
    Degree 2^1: 2181 (30.57%)
    Degree 2^2: 3085 (43.24%)
    Degree 2^3: 621 (8.70%)
    Degree 2^4: 80 (1.12%)
    Degree 2^5: 0 (0.00%)
    Degree 2^6: 1 (0.01%)

[/home/mosama/research/gunrock/gunrock/util/array_utils.cuh, 176 @ gpu 0] in_length_out cudaHostRegister failed. (CUDA error 30: unknown error)
[/home/mosama/research/gunrock/tests/bfs/test_bfs.cu, 382 @ gpu 0] BFS Problem Init failed (CUDA error 30: unknown error)
Source vertex: 0
Using 1 GPU: [ 0 ].

 [BFS] finished.
 avg. elapsed: 0.0000 ms
 iterations: 0
 load time: 432.9090 ms
 preprocess time: 0.0000 ms
 postprocess time: 0.0000 ms
 total time: 435.9961 ms
```

**Comment by sgpyc** [comment] 2016-09-13 01:56
I think it's more of a configuration issue than GTX 1070 vs. GTX 1080. Any other computer has GTX 1080?

**Comment by neoblizz** [comment] 2016-09-13 01:58
My home machine does, but I won't be able to test it until tomorrow night.

**Comment by sgpyc** [comment] 2016-09-13 02:00
I can swap my GTX 1070 with the 1080 on midas latter tonight.

**Comment by neoblizz** [comment] 2016-09-13 02:02
I don't think it is that, they have the same arch. I am going to look more into midas settings.

**Comment by neoblizz** [comment] 2016-09-13 02:24
It fails on compute arch 3.5 with CUDA 7.5 as well;

```
mosama@midas:~/research/gunrock/build$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found CUDA: /usr/local/cuda-7.5 (found suitable version "7.5", minimum required is "7.5") 
-- Boost version: 1.61.0
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found OpenMP
-- Found Metis
-- Project Added: bc
-- Project Added: bfs
-- Project Added: cc
-- Project Added: pr
-- Project Added: sssp
-- Project Added: hits
-- Project Added: salsa
-- Project Added: wtf
-- Project Added: topk
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mosama/research/gunrock/build
```

**Comment by neoblizz** [comment] 2016-09-13 02:31
@sgpyc can you please tell me what driver do you have installed for your 1070? `cat /proc/driver/nvidia/version`

**Comment by sgpyc** [comment] 2016-09-13 03:03
there is some issue of using cudaHostRegister() on midas, which gives out cudaErrorUnknown.
the simpleStreams program in cuda library sample (cuda-8.0/samples/0_Simple/simpleStreams) can reproduce the same error, as following:
sgpyc@midas:~/cuda-8.0-samples/0_Simple/simpleStreams$ ./simpleStreams 
[ simpleStreams ]

Device synchronization method set to = 0 (Automatic Blocking)
Setting reps to 100 to demonstrate steady state

> GPU Device 0: "GeForce GTX 1080" with compute capability 6.1

Device: <GeForce GTX 1080> canMapHostMemory: Yes
> CUDA Capable: SM 6.1 hardware
> 20 Multiprocessor(s) x 128 (Cores/Multiprocessor) = 2560 (Cores)
> scale_factor = 1.0000
> array_size   = 16777216

> Using CPU/GPU Device Synchronization method (cudaDeviceScheduleAuto)
> mmap() allocating 64.00 Mbytes (generic page-aligned system memory)
> cudaHostRegister() registering 64.00 Mbytes of generic allocated system memory
CUDA error at simpleStreams.cu:117 code=30(cudaErrorUnknown) "cudaHostRegister(*ppAligned_a, nbytes, cudaHostRegisterMapped)"

the K20c on midas can pass the same test (using "--device=1" as command line argument to simpleStreams), as following:
sgpyc@midas:~/cuda-8.0-samples/0_Simple/simpleStreams$ ./simpleStreams --device=1
[ simpleStreams ]

Device synchronization method set to = 0 (Automatic Blocking)
Setting reps to 100 to demonstrate steady state

> gpuDeviceInit() CUDA Device [1]: "Tesla K20c
Device: <Tesla K20c> canMapHostMemory: Yes
> CUDA Capable: SM 3.5 hardware
> 13 Multiprocessor(s) x 192 (Cores/Multiprocessor) = 2496 (Cores)
> scale_factor = 1.0000
> array_size   = 16777216

> Using CPU/GPU Device Synchronization method (cudaDeviceScheduleAuto)
> mmap() allocating 64.00 Mbytes (generic page-aligned system memory)
> cudaHostRegister() registering 64.00 Mbytes of generic allocated system memory

Starting Test
memcopy:	13.60
kernel:		4.71
non-streamed:	17.98
4 streams:	13.35

I guess it's somehow related to how the GPU is plugged in / configured.

**Comment by sgpyc** [comment] 2016-09-13 03:05
it's the same version as midas, 367.44, the latest one for 64bit Linux.

It's not a driver issue, since the K20c on Midas can pass the test.

**Comment by yzhwang** [comment] 2016-09-13 04:56
I agree with @sgpyc as I ran into the exact same problem.

**Comment by yzhwang** [comment] 2016-10-01 04:20
@neoblizz You said the problem is fixed right? Please confirm and close the issue if the cudaHostRegister problem has been fixed.

**Comment by neoblizz** [comment] 2016-10-01 05:44
@yzhwang tested and fixed!

**Closed by neoblizz** 2016-10-01 05:44 UTC
