### ISSUE TITLE
CUDA error when running Gunrock on GV100/GP100/Titan V

### ISSUE THREAD

**Issue by Hugovb7** [gunrock/gunrock#358] opened 2018-07-13 12:36 UTC
When running Gunrock's test cases on GV100/GP100/Titan V, we've been seeing a few issues. Here's the details : 

**Description:**

Run Gunrock on GV100,TitanV,GP100 with CUDA 9.2.148 + Driver 396.37,there is CUDA error in some test cases like:rmat_n24_e16.pr,rmat_n23_e32.pr,hollywood-2009.pr or some other pr test.

The error on GV100 and GP100:

[/home/jzhong/Gunrock/gunrock/app/pr/pr_enactor.cuh, 1474 @ gpu 1] cudaStreamSynchronize failed (CUDA error 77: an illegal memory access was encountered)

The error on Titan V is:

[/home/jzhong/Gunrock/gunrock/util/array_utils.cuh, 209 @ gpu 1]  cudaMalloc failed (CUDA error 2: out of memory)
[/home/jzhong/Gunrock/gunrock/util/array_utils.cuh, 532 @ gpu 1] row_offsets cudaMemcpy H2D failed (CUDA error 11: invalid argument)
[/home/jzhong/Gunrock/tests/bfs/test_bfs.cu, 382 @ gpu 1] BFS Problem Init failed (CUDA error 11: invalid argument)

Notes:
I run all the test for 3 times,the error maybe not occur when run first time,but may occur when run the test for second or third time.
The failed test cases is intermittent not on a specific test case.

Detail test log :

[rmat_n22_e64.pr.2.log_TitanV.txt](https://github.com/gunrock/gunrock/files/2192602/rmat_n22_e64.pr.2.log_TitanV.txt)
[soc-orkut.pr.2.log_GV100.txt](https://github.com/gunrock/gunrock/files/2192603/soc-orkut.pr.2.log_GV100.txt)
[rmat_n23_e32.pr.3.log_P100.txt](https://github.com/gunrock/gunrock/files/2192604/rmat_n23_e32.pr.3.log_P100.txt)

**Comment by jowens** [comment] 2018-07-13 12:38
Just for completeness, did you do these tests on previous microarchitectures (Kepler)? Is this a Volta-only failure?

**Comment by Hugovb7** [comment] 2018-07-13 12:46
We also have the bug for Pascal (GP100). I can check for Kepler.

**Comment by neoblizz** [comment] 2018-07-13 15:05
Can you share other installation settings? Like the output of `cmake ..` in a new director? (Boost version, etc.)

**Comment by neoblizz** [comment] 2018-07-13 19:32
```
mosama@mario:~/forks/main/gunrock$ ./build/bin/pr grmat --rmat_scale=22 --rmat_edgefactor=64 --quick --iteration-num=10 --max-iter=1 --device=1 --traversal-mode=LB --json
Generating R-MAT graph ...
rmat_seed = 1531505249
  Converting 4194304 vertices, 536870912 directed edges (unordered tuples) to CSR format...
Done converting (3121s).
R-MAT graph generated in 3125739.000 ms, a = 0.570, b = 0.190, c = 0.190, d = 0.050

Degree Histogram (4194304 vertices, 484085254 edges):
    Degree   0: 1085665 (25.88%)
    Degree 2^0: 459311 (10.95%)
    Degree 2^1: 482543 (11.50%)
    Degree 2^2: 428460 (10.22%)
    Degree 2^3: 508085 (12.11%)
    Degree 2^4: 174886 (4.17%)
    Degree 2^5: 454848 (10.84%)
    Degree 2^6: 175231 (4.18%)
    Degree 2^7: 144675 (3.45%)
    Degree 2^8: 170544 (4.07%)
    Degree 2^9: 0 (0.00%)
    Degree 2^10: 74613 (1.78%)
    Degree 2^11: 26334 (0.63%)
    Degree 2^12: 0 (0.00%)
    Degree 2^13: 7315 (0.17%)
    Degree 2^14: 1540 (0.04%)
    Degree 2^15: 0 (0.00%)
    Degree 2^16: 231 (0.01%)
    Degree 2^17: 22 (0.00%)
    Degree 2^18: 1 (0.00%)

Using 1 GPU(s): [ 1 ].
Using traversal mode LB
-1	 -1	 -1	 scanned_edges 	 oversize :	 2 ->	 4194306
__________________________
--------------------------
iteration 0 elapsed: 51.180124 ms
__________________________
--------------------------
iteration 1 elapsed: 49.171209 ms
__________________________
--------------------------
iteration 2 elapsed: 49.000978 ms
__________________________
--------------------------
iteration 3 elapsed: 48.727036 ms
__________________________
--------------------------
iteration 4 elapsed: 47.837019 ms
__________________________
--------------------------
iteration 5 elapsed: 50.374985 ms
__________________________
--------------------------
iteration 6 elapsed: 49.266100 ms
__________________________
--------------------------
iteration 7 elapsed: 48.127890 ms
__________________________
--------------------------
iteration 8 elapsed: 50.508022 ms
__________________________
--------------------------
iteration 9 elapsed: 48.728943 ms
Total rank : 629145.4999401569

Top 10 Ranked Vertices and PageRanks:
Vertex ID: 111, PageRank: 1.49999991e-01
Vertex ID: 349, PageRank: 1.49999991e-01
Vertex ID: 634, PageRank: 1.49999991e-01
Vertex ID: 636, PageRank: 1.49999991e-01
Vertex ID: 1191, PageRank: 1.49999991e-01
Vertex ID: 1358, PageRank: 1.49999991e-01
Vertex ID: 1443, PageRank: 1.49999991e-01
Vertex ID: 1496, PageRank: 1.49999991e-01
Vertex ID: 1656, PageRank: 1.49999991e-01
Vertex ID: 1960, PageRank: 1.49999991e-01

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_1	 2088763392	 2	 2
	 queue_sizing =	 0.000000 	 0.000000

 [PageRank] finished.
 avg. elapsed: 49.2922 ms
 iterations: 1
 min. elapsed: 47.8370 ms
 max. elapsed: 51.1801 ms
 rate: 9820.7217 MiEdges/s
 src: 0
 nodes_visited: 4194304
 edges_visited: 484085254
 edges queued: 484085254
 load time: 3125860.1990 ms
 preprocess time: 911.8400 ms
 postprocess time: 79.6580 ms
 total time: 3127353.0819 ms

{
    "64bit_SizeT" : false,
    "64bit_Value" : false,
    "64bit_VertexId" : false,
    "algorithm" : "PageRank",
    "alpha" : 6,
    "average_duty" : 0,
    "beta" : 6,
    "command_line" : "./build/bin/pr grmat --rmat_scale=22 --rmat_edgefactor=64 --quick --iteration-num=10 --max-iter=1 --device=1 --traversal-mode=LB --json",
    "communicate_latency" : 0,
    "communicate_multipy" : -1,
    "compensate" : false,
    "compiler" : "Gnu GCC C/C++",
    "compiler_version" : 50400000,
    "dataset" : "rmat_n22_e64",
    "debug_mode" : false,
    "delta" : 0.85000002384185791,
    "delta_factor" : 16,
    "destination_vertex" : 4194303,
    "device_list" : [
        1
    ],
    "direction_optimized" : false,
    "do_a" : 0.001,
    "do_b" : 0.20000000000000001,
    "duplicate_graph" : false,
    "edge_value" : false,
    "edges_queued" : 484085254,
    "edges_redundance" : 0,
    "edges_visited" : 484085254,
    "elapsed" : 49.292230606079102,
    "engine" : "Gunrock",
    "error" : 0.0099999997764825821,
    "expand_latency" : 0,
    "fullqueue_latency" : 0,
    "git_commit_sha1" : "6b7b3e5fddb95feda52dfa83992c51a8e4c14663",
    "gpuinfo" : {
        "clock_rate" : 1455000,
        "compute_version" : 70,
        "driver_api" : 9020,
        "driver_version" : 9020,
        "major" : 7,
        "minor" : 0,
        "multi_processor_count" : 80,
        "name" : "TITAN V",
        "runtime_version" : 9020,
        "total_global_mem" : 12652838912
    },
    "graph_type" : "grmat",
    "gunrock_version" : "0.4.0",
    "idempotent" : false,
    "instrument" : false,
    "json" : true,
    "jsondir" : "",
    "jsonfile" : "",
    "label" : "",
    "load_time" : 3125860.1989746094,
    "m_teps" : 9820.7216796875,
    "makeout_latency" : 0,
    "mark_predecessors" : false,
    "max_grid_size" : 0,
    "max_in_sizing" : -1,
    "max_iteration" : 1,
    "max_process_time" : 51.180124282836914,
    "max_queue_sizing" : -1,
    "max_queue_sizing1" : -1,
    "min_process_time" : 47.837018966674805,
    "multi_graphs" : false,
    "node_value" : false,
    "nodes_queued" : 0,
    "nodes_redundance" : 0,
    "nodes_visited" : 4194304,
    "normalized" : false,
    "num_edges" : 484085254,
    "num_gpus" : 1,
    "num_iteration" : 10,
    "num_vertices" : 4194304,
    "output_filename" : "",
    "partition_factor" : -1,
    "partition_method" : "random",
    "partition_seed" : -1,
    "postprocess_time" : 79.658031463623047,
    "preprocess_time" : 911.83996200561523,
    "process_times" : [
        51.180124282836914,
        49.171209335327148,
        49.000978469848633,
        48.727035522460938,
        47.837018966674805,
        50.374984741210938,
        49.26609992980957,
        48.127889633178711,
        50.508022308349609,
        48.72894287109375
    ],
    "quick_mode" : true,
    "quiet_mode" : false,
    "random_edge_value" : false,
    "ref_filename" : "",
    "rmat_a" : 0.56999999999999995,
    "rmat_b" : 0.19,
    "rmat_c" : 0.19,
    "rmat_d" : 0.050000000000000044,
    "rmat_edgefactor" : 64,
    "rmat_edges" : 268435456,
    "rmat_nodes" : 4194304,
    "rmat_scale" : 22,
    "rmat_seed" : -1,
    "rmat_vmin" : 1,
    "rmat_vmultipiler" : 64,
    "scaled" : false,
    "search_depth" : 1,
    "size_check" : true,
    "source_seed" : 0,
    "source_type" : "",
    "source_vertex" : 0,
    "stddev_degrees" : 1115,
    "stream_from_host" : false,
    "subqueue_latency" : 0,
    "sysinfo" : {
        "machine" : "x86_64",
        "nodename" : "mario",
        "release" : "4.4.0-128-generic",
        "sysname" : "Linux",
        "version" : "#154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018"
    },
    "time" : "Fri Jul 13 11:59:35 2018\n",
    "top_nodes" : 0,
    "total_time" : 3127353.0819416046,
    "traversal_mode" : "LB",
    "undirected" : true,
    "userinfo" : {
        "login" : "mosama"
    },
    "walk_length" : 1,
    "write_time" : 0
}
```

```
mosama@mario:~/forks/main/gunrock$ uname -r
4.4.0-128-generic

Driver Version: 396.26


mosama@mario:~/forks/main/gunrock$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88
```


I am gonna try recreating with with the updated driver/cuda version.

**Comment by jowens** [comment] 2018-07-13 19:37
@neoblizz are you saying it worked for you (on Titan V)? (Do try multiple runs since @Hugovb7 said it was intermittent.)

**Comment by neoblizz** [comment] 2018-07-13 20:09
@jowens yeah, it is working for me. But I have slightly different driver/cuda version (still 9.2). I am running it a few more times.

**Comment by neoblizz** [comment] 2018-07-13 23:04
Two more runs: [TitanV-PR.txt](https://github.com/gunrock/gunrock/files/2194413/TitanV-PR.txt)

Next step; I will update nvidia driver tonight.

**Comment by neoblizz** [comment] 2018-07-15 19:11
[issue#358.txt](https://github.com/gunrock/gunrock/files/2196018/issue.358.txt)

**Comment by Hugovb7** [comment] 2018-07-19 14:07
@neoblizz  , OS is Ubuntu 16.04.4. I'll post the output of cmake

**Comment by Hugovb7** [comment] 2018-07-19 14:13
@neoblizz Also, this issue does not exist on Kepler

**Comment by ctcyang** [comment] 2018-07-24 23:19
As another datapoint, all tests pass on Tesla V100 (16GB), 9.0.176 + Driver 384.111, Boost 1.58.0, GCC 5.4.0

```
Test project /home/ubuntu/master/gunrock/build
      Start  1: TEST_BFS
 1/11 Test  #1: TEST_BFS .........................   Passed   30.95 sec
      Start  2: TEST_BC
 2/11 Test  #2: TEST_BC ..........................   Passed    4.65 sec
      Start  3: TEST_CC
 3/11 Test  #3: TEST_CC ..........................   Passed    1.90 sec
      Start  4: TEST_SSSP
 4/11 Test  #4: TEST_SSSP ........................   Passed    5.75 sec
      Start  5: TEST_PAGERANK
 5/11 Test  #5: TEST_PAGERANK ....................   Passed    7.82 sec
      Start  6: TEST_TOPK
 6/11 Test  #6: TEST_TOPK ........................   Passed    2.54 sec
      Start  7: SHARED_LIB_TEST_BFS
 7/11 Test  #7: SHARED_LIB_TEST_BFS ..............   Passed   12.57 sec
      Start  8: SHARED_LIB_TEST_BC
 8/11 Test  #8: SHARED_LIB_TEST_BC ...............   Passed    0.85 sec
      Start  9: SHARED_LIB_TEST_CC
 9/11 Test  #9: SHARED_LIB_TEST_CC ...............   Passed    0.84 sec
      Start 10: SHARED_LIB_TEST_SSSP
10/11 Test #10: SHARED_LIB_TEST_SSSP .............   Passed    0.83 sec
      Start 11: SHARED_LIB_TEST_PAGERANK
11/11 Test #11: SHARED_LIB_TEST_PAGERANK .........   Passed    0.85 sec

100% tests passed, 0 tests failed out of 11

Total Test time (real) =  69.56 sec
Built target check
```

It might be your Boost installation like @neoblizz pointed out

**Comment by Hugovb7** [comment] 2018-07-30 16:56
Thanks @ctcyang . I'm indeed not able to reproduce this bug on another machine using this exact configuration. We're trying to locate the source, I'll keep you updated.

Thanks!

**Comment by neoblizz** [comment] 2018-07-30 19:06
@Hugovb7 I'll still be curious to see your cmake output, that usually has all the info we need. You should definitely look at the boost version too.

**Comment by Hugovb7** [comment] 2018-07-31 17:55
@neoblizz Here's the outputs from the commands during the build process :

[07_make.log](https://github.com/gunrock/gunrock/files/2246504/07_make.log)
[06_cmake.log](https://github.com/gunrock/gunrock/files/2246505/06_cmake.log)
[05_submodule_checkout.log](https://github.com/gunrock/gunrock/files/2246506/05_submodule_checkout.log)
[04_submodule_clone.log](https://github.com/gunrock/gunrock/files/2246507/04_submodule_clone.log)
[03_submodule_checkout.log](https://github.com/gunrock/gunrock/files/2246508/03_submodule_checkout.log)
[02_submodule_clone.log](https://github.com/gunrock/gunrock/files/2246509/02_submodule_clone.log)
[01_git_pull.log](https://github.com/gunrock/gunrock/files/2246510/01_git_pull.log)

We were able to reproduce the bug on another machine. The bug is intermittent, it usually takes ~10 runs of ctest to detect it.

Please let me know if I can provide any more info.

**Comment by Hugovb7** [comment] 2018-08-06 20:05
If by any chance I can help you reproduce the bug please let me know!

**Comment by neoblizz** [comment] 2018-08-06 20:12
I think I was able to reproduce this as well, I am gonna debug this maybe later in the week. Busy with some other stuff right now. Thank you for providing all the logs, I will report back here. @Hugovb7

**Comment by Hugovb7** [comment] 2018-09-06 22:19
@neoblizz just wanted to check if you were able to take a look ?

**Comment by neoblizz** [comment] 2018-09-06 22:28
I think there is a bug in PR, I have asked @sgpyc to check it out.

**Comment by Hugovb7** [comment] 2018-09-11 19:45
@sgpyc were you able to reproduce with nvidia driver 396 ?

**Comment by jowens** [comment] 2018-09-11 19:47
@Hugovb7 Kind of not fair to ask us to roll back to a previous driver to test something if it's fixed in a later driver ... that would tend to indicate that the problem was with the driver and has been fixed as opposed to a problem with our code. Am I missing something here?

**Comment by sgpyc** [comment] 2018-09-11 19:58
Not rolling back the driver, but I can try to test within a docker with older driver. If the issue can be reproduced, that confirms the bug is with the driver and has been resolved in some newer version

**Comment by Hugovb7** [comment] 2018-09-11 20:30
@jowens Like @sgpyc said, it's just to make sure that the driver actually fixed the issue. I'll try it myself, but if you already have the info, I was interested. If it is confirmed that the driver was the problem it's of course not necessary to fix it within gunrock :)

@sgpyc Usually you won't be able to have the cuda driver inside of the docker image - the host driver is used.

**Comment by Hugovb7** [comment] 2018-09-14 18:28
My bad, this bug actually looks fixed by 410. Got confused with #359, which is still there

**Comment by neoblizz** [comment] 2018-09-14 18:30
Yeah, I don't see any PR errors there. So, assuming it was a driver issue, I am closing the PageRank issue. Let's discuss `BC` in #359. Which is what failed:

```
Muhammad_Osama@Blizzard-M:~/Desktop/Run_Gunrock$ grep -nr 'TEST_BC' .
./ctest.8.log:74:      Start  2: TEST_BC
./ctest.8.log:129: 2/11 Test  #2: TEST_BC ..........................   Passed    2.25 sec
./ctest.8.log:375:      Start  8: SHARED_LIB_TEST_BC
./ctest.8.log:388: 8/11 Test  #8: SHARED_LIB_TEST_BC ...............   Passed    2.27 sec
./ctest.9.log:74:      Start  2: TEST_BC
./ctest.9.log:129: 2/11 Test  #2: TEST_BC ..........................   Passed    2.24 sec
./ctest.9.log:375:      Start  8: SHARED_LIB_TEST_BC
./ctest.9.log:388: 8/11 Test  #8: SHARED_LIB_TEST_BC ...............   Passed    2.27 sec
./summary.log:13:---- SHARED_LIB_TEST_BC ----
./summary.log:43:---- TEST_BC ----
./ctest.10.log:74:      Start  2: TEST_BC
./ctest.10.log:129: 2/11 Test  #2: TEST_BC ..........................   Passed    2.24 sec
./ctest.10.log:375:      Start  8: SHARED_LIB_TEST_BC
./ctest.10.log:388: 8/11 Test  #8: SHARED_LIB_TEST_BC ...............   Passed    2.29 sec
./ctest.1.log:76:      Start  2: TEST_BC
./ctest.1.log:155: 2/11 Test  #2: TEST_BC ..........................***Failed  Error regular expression found in output. Regex=[INCORRECT]  5.86 sec
./ctest.1.log:403:      Start  8: SHARED_LIB_TEST_BC
./ctest.1.log:414: 8/11 Test  #8: SHARED_LIB_TEST_BC ...............***Failed  Required regular expression not found.Regex=[Node_ID.*0.*: Score.*0.5000
./ctest.1.log:466:	  2 - TEST_BC (Failed)
./ctest.1.log:467:	  8 - SHARED_LIB_TEST_BC (Failed)
./ctest.2.log:74:      Start  2: TEST_BC
./ctest.2.log:129: 2/11 Test  #2: TEST_BC ..........................   Passed    2.24 sec
./ctest.2.log:375:      Start  8: SHARED_LIB_TEST_BC
./ctest.2.log:386: 8/11 Test  #8: SHARED_LIB_TEST_BC ...............***Failed  Required regular expression not found.Regex=[Node_ID.*0.*: Score.*0.5000
./ctest.2.log:438:	  8 - SHARED_LIB_TEST_BC (Failed)
./ctest.3.log:74:      Start  2: TEST_BC
./ctest.3.log:129: 2/11 Test  #2: TEST_BC ..........................   Passed    2.25 sec
./ctest.3.log:375:      Start  8: SHARED_LIB_TEST_BC
./ctest.3.log:388: 8/11 Test  #8: SHARED_LIB_TEST_BC ...............   Passed    2.27 sec
./ctest.7.log:74:      Start  2: TEST_BC
./ctest.7.log:129: 2/11 Test  #2: TEST_BC ..........................   Passed    2.24 sec
./ctest.7.log:375:      Start  8: SHARED_LIB_TEST_BC
./ctest.7.log:387: 8/11 Test  #8: SHARED_LIB_TEST_BC ...............   Passed    2.27 sec
./ctest.6.log:74:      Start  2: TEST_BC
./ctest.6.log:129: 2/11 Test  #2: TEST_BC ..........................   Passed    2.24 sec
./ctest.6.log:375:      Start  8: SHARED_LIB_TEST_BC
./ctest.6.log:388: 8/11 Test  #8: SHARED_LIB_TEST_BC ...............   Passed    2.29 sec
./ctest.4.log:74:      Start  2: TEST_BC
./ctest.4.log:153: 2/11 Test  #2: TEST_BC ..........................***Failed  Error regular expression found in output. Regex=[INCORRECT]  2.24 sec
./ctest.4.log:399:      Start  8: SHARED_LIB_TEST_BC
./ctest.4.log:410: 8/11 Test  #8: SHARED_LIB_TEST_BC ...............***Failed  Required regular expression not found.Regex=[Node_ID.*0.*: Score.*0.5000
./ctest.4.log:462:	  2 - TEST_BC (Failed)
./ctest.4.log:463:	  8 - SHARED_LIB_TEST_BC (Failed)
./ctest.5.log:74:      Start  2: TEST_BC
./ctest.5.log:129: 2/11 Test  #2: TEST_BC ..........................   Passed    2.24 sec
./ctest.5.log:375:      Start  8: SHARED_LIB_TEST_BC
./ctest.5.log:388: 8/11 Test  #8: SHARED_LIB_TEST_BC ...............   Passed    2.26 sec
```

**Closed by neoblizz** 2018-09-14 18:30 UTC
Labels: bug
